"""Added Booking model

Revision ID: 6d3c8a87bd94
Revises: 8e13b0165192
Create Date: 2026-05-13 21:31:51.401250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3c8a87bd94'
down_revision = '8e13b0165192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('booking_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('charging_duration', sa.Integer(), nullable=False),
    sa.Column('booking_status', sa.String(length=20), server_default=sa.text("'confirmed'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('charging_duration > 0', name='ck_bookings_charging_duration_positive'),
    sa.ForeignKeyConstraint(['station_id'], ['charging_stations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_station_id'), ['station_id'], unique=False)
        batch_op.create_index('ix_bookings_station_time_status', ['station_id', 'booking_time', 'booking_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_bookings_user_station_status', ['user_id', 'station_id', 'booking_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('ix_bookings_user_station_status')
        batch_op.drop_index(batch_op.f('ix_bookings_user_id'))
        batch_op.drop_index('ix_bookings_station_time_status')
        batch_op.drop_index(batch_op.f('ix_bookings_station_id'))

    op.drop_table('bookings')
    # ### end Alembic commands ###
