"""Added ChargingStation model

Revision ID: 8e13b0165192
Revises: f6aeb7fbc731
Create Date: 2026-05-13 18:46:17.155542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e13b0165192'
down_revision = 'f6aeb7fbc731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charging_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('total_slots', sa.Integer(), nullable=False),
    sa.Column('available_slots', sa.Integer(), nullable=False),
    sa.Column('charging_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charging_stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charging_stations_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_charging_stations_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_charging_stations_station_name'), ['station_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charging_stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charging_stations_station_name'))
        batch_op.drop_index(batch_op.f('ix_charging_stations_state'))
        batch_op.drop_index(batch_op.f('ix_charging_stations_city'))

    op.drop_table('charging_stations')
    # ### end Alembic commands ###
