"""Add role column to users table

Revision ID: a7b2c4d5e6f7
Revises: 6d3c8a87bd94
Create Date: 2026-05-13 22:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b2c4d5e6f7'
down_revision = '6d3c8a87bd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
